// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Js_array from "rescript/lib/es6/js_array.js";

function empty(param) {
  return [];
}

function insert(item, set) {
  if (Js_array.includes(item, set)) {
    return set;
  } else {
    set.push(item);
    return set;
  }
}

function make(arr) {
  var ret = [];
  arr.forEach(function (i) {
        insert(i, ret);
      });
  return ret;
}

var contains = Js_array.includes;

function remove(item, set) {
  return Js_array.filter((function (i) {
                return Caml_obj.notequal(i, item);
              }), set);
}

function union(set1, set2) {
  var result = make(set1);
  set2.forEach(function (item) {
        insert(item, result);
      });
  return result;
}

var $$Set = {
  empty: empty,
  insert: insert,
  make: make,
  contains: contains,
  remove: remove,
  union: union
};

export {
  $$Set ,
}
/* No side effect */
