// Generated by ReScript, PLEASE EDIT WITH CARE


function slice(_xs, _s, l) {
  while(true) {
    var s = _s;
    var xs = _xs;
    if (!xs) {
      return /* [] */0;
    }
    if (s === 0 && l === 0) {
      return /* [] */0;
    }
    var xss = xs.tl;
    if (s === 0) {
      return {
              hd: xs.hd,
              tl: slice(xss, 0, l - 1 | 0)
            };
    }
    _s = s - 1 | 0;
    _xs = xss;
    continue ;
  };
}

function printList(_xs) {
  while(true) {
    var xs = _xs;
    if (xs) {
      console.log(xs.hd);
      _xs = xs.tl;
      continue ;
    }
    console.log("\n");
    return ;
  };
}

var Utils = {
  slice: slice,
  printList: printList
};

export {
  Utils ,
}
/* No side effect */
